// src/components/BackTop.vue
<script setup lang="ts">
import MdiArrowTopBold from '~icons/mdi/arrow-top-bold';

const backTop = () => {
  scrollTo({
    top: 0,
    behavior: 'smooth'
  });
};

const isVisible = ref(false);

function checkVisible() {
  isVisible.value = window.scrollY > 300;
}

onMounted(() => {
  window.addEventListener('scroll', checkVisible);
});

onUnmounted(() => {
  window.removeEventListener('scroll', checkVisible)
});
</script>

<template>
  <Transition>
    <div v-if="isVisible" fixed bottom-8 right-8 text-2xl text-stone cursor-pointer transition-all duration-300
      hover="text-stone-9 transition-all" @click="backTop">
      <MdiArrowTopBold />
    </div>
  </Transition>
</template>

<style>
.v-enter-active,
.v-leave-active {
  transition: opacity 0.3s ease;
}

.v-enter-from,
.v-leave-to {
  opacity: 0;
}
</style>

// apps/site/src/components/back-top.tsx
import { useEffect, useState } from "react"

export default function BackTop() {
  const [visible, setVisible] = useState(false)

  function checkVisible() {
    setVisible(window.scrollY > 300)
  }

  useEffect(() => {
    window.addEventListener("scroll", checkVisible)
    return () => {
      window.removeEventListener("scroll", checkVisible)
    }
  }, [])

  function scrollToTop() {
    window.scrollTo({
      top: 0,
      behavior: "smooth"
    })
  }

  const fadeInOut = visible ? 'opacity-100' : 'opacity-0'

  return (
    <div className={`${fadeInOut} fixed bottom-8 right-8 text-2xl text-stone cursor-pointer transition-all duration-300 hover:(text-stone-9 transition-all)`} onClick={scrollToTop}>
      <div className="i-mdi:arrow-top-bold w-7 h-7" />
    </div>
  )
}
