// apps/site/src/components/color-mode-switch.tsx
import { useRef, useState } from "react"
import { colorModeEffect, Mode } from "@/common/color-mode"

const modes = [
  {
    icon: 'i-mingcute:sun-line',
    mode: Mode.Light
  },
  {
    icon: 'i-mingcute:computer-line',
    mode: Mode.System
  },
  {
    icon: 'i-mingcute:moon-line',
    mode: Mode.Dark
  }
]

const colorMode = colorModeEffect()

colorMode.onFollowSystem()


export default function colorModeSwitch() {
  const switchWrapper = useRef<HTMLDivElement>(null)
  const buttons = useRef<HTMLButtonElement[]>([])

  const [mode, setMode] = useState(colorMode.initial)

  const [isActive, setIsActive] = useState(false)
  const [sliderX, setSliderX] = useState(4)

  let timeLock = false
  function timeoutTimeLock() {
    timeLock = true
    setTimeout(() => {
      timeLock = false
    }, 200);
  }

  function setActive(value: boolean) {
    if (isActive === value) {
      return
    }

    if (true) {
      const matchIndex = modes.findIndex(item => item.mode === mode)
      const targetButton = buttons.current[matchIndex]
      const parent = targetButton.parentElement!
      const x = targetButton.getBoundingClientRect().left - parent.getBoundingClientRect().left
      setSliderX(x)
    }

    timeoutTimeLock()
    setIsActive(value)
  }

  function handleSwitchClick(buttonIndex: number, targetMode: Mode) {
    if (timeLock) {
      return
    }

    const targetElement = buttons.current[buttonIndex]
    const wrapperRect = switchWrapper.current!.getBoundingClientRect()
    const rect = targetElement.getBoundingClientRect()

    setSliderX(rect.left - wrapperRect.left)
    setMode(targetMode)
    colorMode.appendToDocument(targetMode)
  }


  const textOpacity = isActive ? 'text-opacity-100' : 'text-opacity-0'
  const iconSize = 'w-4 h-4'

  return (
    <div
      ref={switchWrapper}
      className="w-8 hover:w-23 overflow-hidden transition-x duration-200 transform-gpu rounded-full"
      onMouseOver={() => setActive(true)}
      onMouseLeave={() => setActive(false)}
    >
      <div 
        className={`box-border w-23 bg-cool-gray-100 dark:bg-true-gray-700 p-1 flex justify-center items-center gap-1 shadow-inner text-xs text-true-gray-400  transform relative  ${textOpacity}`}
        style={{ '--status-x': `${sliderX}px` }}
      >
        <div 
          className={`w-6 h-6 flex items-center justify-center bg-light-50 dark:(bg-dark text-light-50) rounded-full shadow absolute text-black ${isActive ? 'left-$status-x' : 'left-1'} z-99 translate-x duration-100`}
        >
          {modes.map((item) => (
            item.mode === mode && <div key={item.mode} className={`${item.icon} ${iconSize}`}></div>
          ))}
        </div>

        {modes.map((item, index) => (
          <button
            ref={(el) => { (buttons.current[index] = el!) }}
            key={item.mode}
            className="w-6 h-6 flex items-center justify-center relative before:content-[''] before:(absolute top-0 left-0 right-0 bottom-0)"
            onClick={() => handleSwitchClick(index, item.mode)}
          >
            <div className={`${item.icon} ${iconSize}`}></div>
          </button>
        ))}
      </div>
    </div>
  )
}

// src/components/vue/ColorModeSwitch.vue
<script lang="ts" setup>
import MingcuteSunLine from '~icons/mingcute/sun-line';
import MingcuteComputerLine from '~icons/mingcute/computer-line';
import MingcuteMoonLine from '~icons/mingcute/moon-line';
import { Mode, colorModeEffect } from '../../common/colorMode';

const modes = [
  {
    icon: MingcuteSunLine,
    mode: Mode.Light
  },
  {
    icon: MingcuteComputerLine,
    mode: Mode.System
  },
  {
    icon: MingcuteMoonLine,
    mode: Mode.Dark
  }
]

const colorMode = colorModeEffect()
const mode = ref(colorMode.initial)

colorMode.onFollowSystem()

const switchWrapper = ref<HTMLDivElement>()
const buttons = ref<HTMLButtonElement[]>([])

const sliderX = ref(4)
const isActive = ref(false)

function setIsActive(value: boolean) {
  if (isActive.value === value) {
    return
  }

  if (true) {
    const matchIndex = modes.findIndex(item => item.mode === mode.value)
    const targetButton = buttons.value[matchIndex]
    const parent = targetButton.parentElement!
    const x = targetButton.getBoundingClientRect().left - parent.getBoundingClientRect().left
    sliderX.value = x
  }

  timeoutTimeLock()
  isActive.value = value
}

const timeLock = ref(false)
function timeoutTimeLock() {
  timeLock.value = true
  setTimeout(() => {
    timeLock.value = false
  }, 200);
}

function handleSwitchClick(event: MouseEvent, targetMode: Mode) {
  if (timeLock.value) {
    return
  }

  const targetElement = event.target as Element
  const parent = targetElement.parentElement!
  const parentRect = parent.getBoundingClientRect()
  const rect = targetElement.getBoundingClientRect()
  sliderX.value = rect.left - parentRect.left
  mode.value = targetMode
  colorMode.appendToDocument(targetMode)
}
</script>

<template>
  <div
    ref="switchWrapper"
    class="w-8 hover:w-23 overflow-hidden transition-x duration-200 transform-gpu rounded-full"
    @mouseover="setIsActive(true)"
    @mouseleave="setIsActive(false)"
  >
    <div
      :class="`box-border w-23 bg-cool-gray-100 dark:bg-true-gray-700 p-1 flex justify-center items-center gap-1 shadow-inner text-xs text-true-gray-400  transform relative  ${isActive ? 'text-opacity-100' : 'text-opacity-0'}`"
      :style="{ '--status-x': `${sliderX}px` }">
      <div
        :class="`w-6 h-6 flex items-center justify-center bg-light-50 dark:bg-dark dark:text-light-50 rounded-full shadow absolute text-black ${isActive ? 'left-$status-x' : 'left-1'} z-99 translate-x duration-100`">

        <template v-for="item in modes">
          <component :is="item.icon" v-if="item.mode === mode"></component>
        </template>
      </div>

      <button v-for="item in modes" ref="buttons" class="w-6 h-6 flex items-center justify-center relative before:content-['']"
        before="absolute top-0 left-0 right-0 bottom-0" @click="handleSwitchClick($event, item.mode)">
        <component :is="item.icon"></component>
      </button>
    </div>
  </div>
</template>
