// src/components/Image.vue
<script setup lang="ts">
import MdiImageOff from '~icons/mdi/image-off';

defineProps<{
  src: string
  width: string
  height?: string
  alt?: string
  round?: boolean
}>()

const isError = ref(false)

function handleError() {
  isError.value = true
}

</script>

<template>
  <div bg-stone-1 :rounded="round ? 'full' : 'sm'" overflow-hidden flex justify-center items-center border border-stone-2 :style="{ width, height }">
    <img v-if="!isError" :src="src" :alt="alt" @error="handleError" />
    <div v-else flex flex-col justify-center items-center text-stone>
      <MdiImageOff />
      <span text-xs>{{ alt }}</span>
    </div>
  </div>
</template>

// src/components/react/Image.tsx
import { useState } from "react"

interface ImageProps {
  src: string
  width?: string
  height?: string
  alt?: string
  round?: boolean
}

export default function Image({ src, width, height, alt, round }: ImageProps) {
  const [isError, setIsError] = useState(false)

  const rounded = round ? 'full' : 'sm'

  return (
    <div className={`bg-stone-1 overflow-hidden flex justify-center items-center border border-stone-2 ${rounded}`}  style={{ width, height }}>
      {
        isError
          ? <img src={src} alt={alt} onError={() => setIsError(false)} />
          : <div className="flex flex-col justify-center items-center text-stone" >
              <div className="i-mdi:image-off w-6 h-6"></div>
              <span className="text-xs">{ alt }</span>
            </div>
      }
    </div>
  )
}
